(async function(){
  "use strict";
  const state={client:null,session:null,from:"",to:"",page:1,total:0,limit:25,quotes:[],charts:{},timezone:"Africa/Nairobi"};
  const $=(id)=>document.getElementById(id),money=(v)=>new Intl.NumberFormat("en-KE",{style:"currency",currency:"KES",maximumFractionDigits:0}).format(Number(v||0)).replace("Ksh","KES"),date=(v)=>new Intl.DateTimeFormat("en-KE",{dateStyle:"medium",timeZone:state.timezone}).format(new Date(v)),escape=(v)=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]);
  try{const response=await fetch("/api/config"),config=await response.json();if(!response.ok)throw new Error();state.timezone=config.timezone;state.client=window.supabase.createClient(config.supabaseUrl,config.supabaseAnonKey);const{data}=await state.client.auth.getSession();if(!data.session)return location.replace("/orders/login");state.session=data.session;const test=await api("/api/admin/dashboard");if(!test)return;$("auth-loading").classList.add("hidden");$("dashboard").classList.remove("hidden");boot();}catch(error){$("auth-loading").textContent="Unable to load the owner dashboard.";}

  function boot(){const today=isoDate(new Date());$("from").value=today;$("to").value=today;$("current-date").textContent=date(new Date());$("payment-date").value=new Date().toISOString().slice(0,16);bind();applyRange();}
  function bind(){
    $("sign-out").onclick=async()=>{await state.client.auth.signOut();location.replace("/orders/login")};$("refresh").onclick=refresh;$("apply").onclick=()=>{state.page=1;refresh()};$("range").onchange=applyRange;$("export").onclick=exportCsv;$("print-report").onclick=()=>window.print();
    ["search","payment-filter","status-filter","sort"].forEach(id=>$(id).addEventListener("change",()=>{state.page=1;loadQuotes()}));$("search").addEventListener("input",debounce(()=>{state.page=1;loadQuotes()},350));
    $("previous").onclick=()=>{if(state.page>1){state.page--;loadQuotes()}};$("next").onclick=()=>{if(state.page*state.limit<state.total){state.page++;loadQuotes()}};
    $("quote-rows").onclick=$("quote-cards").onclick=handleQuoteAction;$("detail-content").onclick=reversePayment;document.querySelectorAll("[data-close]").forEach(b=>b.onclick=()=>b.closest("dialog").close());$("payment-form").onsubmit=savePayment;$("scan-local").onclick=scanLocal;
  }
  async function api(path,options={}){const headers={"Content-Type":"application/json",Authorization:`Bearer ${state.session.access_token}`,...options.headers};const response=await fetch(path,{...options,headers});if(response.status===401){location.replace("/orders/login");return null}const data=await response.json().catch(()=>({}));if(!response.ok){toast(data.error||"Request failed.",true);if(response.status===403)location.replace("/orders/login");return null}return data;}
  function applyRange(){const now=new Date(),type=$("range").value;let from=new Date(now),to=new Date(now);if(type==="yesterday")from=to=addDays(now,-1);if(type==="7")from=addDays(now,-6);if(type==="30")from=addDays(now,-29);if(type==="week")from=addDays(now,-((now.getDay()+6)%7));if(type==="month")from=new Date(now.getFullYear(),now.getMonth(),1);if(type==="previous-month"){from=new Date(now.getFullYear(),now.getMonth()-1,1);to=new Date(now.getFullYear(),now.getMonth(),0)}if(type==="year")from=new Date(now.getFullYear(),0,1);if(type==="all")from=new Date(2020,0,1);if(type!=="custom"){$("from").value=isoDate(from);$("to").value=isoDate(to)}refresh();}
  async function refresh(){state.from=$("from").value;state.to=$("to").value;if(!state.from||!state.to||state.from>state.to)return toast("Choose a valid date range.",true);$("active-range").textContent=`${state.from} to ${state.to}`;$("refresh").disabled=true;const [dashboard,services]=await Promise.all([api(`/api/admin/dashboard?from=${state.from}&to=${state.to}`),api(`/api/admin/reports/services?from=${state.from}&to=${state.to}`)]);if(dashboard){renderSummary(dashboard.summary);renderCharts(dashboard.charts,services?.services||[]);$("last-refreshed").textContent=new Date().toLocaleTimeString()}await loadQuotes();$("refresh").disabled=false;}
  function renderSummary(s){const mode=$("report-mode").value,quotation=[['Quotations',s.quotations],['Active quotations',s.active],['Voided quotations',s.voided],['Total quoted value',money(s.quotedValue)],['Average quotation',money(s.averageQuote)],['Total discounts',money(s.discounts)],['Total fees',money(s.fees)],['Outstanding balance',money(s.outstanding)]],payment=[['Payments received',money(s.payments)],['Cash received',money(s.cash)],['M-Pesa received',money(s.mpesa)],['Bank received',money(s.bank)],['Card received',money(s.card)],['Other received',money(s.other)],['Reversed payments','See payments'],['Net payments',money(s.payments)]];$("summary-cards").innerHTML=(mode==="payment"?payment:quotation).map(([label,value])=>`<article class="summary-card"><span>${label}</span><strong>${value}</strong></article>`).join("");}
  function chart(id,type,data,options){state.charts[id]?.destroy();state.charts[id]=new Chart($(id),{type,data,options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{position:"bottom"}},...options}})}
  function renderCharts(c,services){const labels=c.daily.map(d=>d.date);chart("daily-chart","line",{labels,datasets:[{label:"Quoted value",data:c.daily.map(d=>d.quoted),borderColor:"#073f78",backgroundColor:"#073f78"},{label:"Payments",data:c.daily.map(d=>d.payments),borderColor:"#05aeba",backgroundColor:"#05aeba"}]},{scales:{y:{ticks:{callback:v=>money(v)}}}});chart("payment-chart","doughnut",{labels:c.paymentMethods.map(x=>x.method),datasets:[{data:c.paymentMethods.map(x=>x.value),backgroundColor:["#073f78","#05aeba","#3c9b69","#e3a12b","#758495"]}]});chart("status-chart","bar",{labels:c.paymentStatus.map(x=>x.status.replace("_"," ")),datasets:[{label:"Quotations",data:c.paymentStatus.map(x=>x.count),backgroundColor:"#05aeba"}]});const top=services.slice(0,8);chart("services-chart","bar",{labels:top.map(x=>x.item),datasets:[{label:"Quoted value",data:top.map(x=>x.value),backgroundColor:"#073f78"}]},{indexAxis:"y"});$("daily-summary").textContent=c.daily.length?`${c.daily.length} reporting days shown.`:"No activity in this range.";$("payment-summary").textContent=c.paymentMethods.map(x=>`${x.method}: ${money(x.value)}`).join("; ");$("status-summary").textContent=c.paymentStatus.map(x=>`${x.status}: ${x.count}`).join("; ");$("services-summary").textContent=top.length?`Highest quoted service: ${top[0].item}, ${money(top[0].value)}.`:"No services in this range.";}
  async function loadQuotes(){const q=new URLSearchParams({from:$("from").value,to:$("to").value,page:state.page,limit:state.limit,search:$("search").value,paymentStatus:$("payment-filter").value,status:$("status-filter").value,sort:$("sort").value});const data=await api(`/api/admin/quotations?${q}`);if(!data)return;state.quotes=data.quotations;state.total=data.total;const rows=data.quotations.map(q=>quoteRow(q)).join("");$("quote-rows").innerHTML=rows||'<tr><td colspan="10">No quotations found.</td></tr>';$("quote-cards").innerHTML=data.quotations.map(q=>quoteCard(q)).join("")||'<p>No quotations found.</p>';$("page-label").textContent=`Page ${state.page} of ${Math.max(1,Math.ceil(state.total/state.limit))}`;$("previous").disabled=state.page<=1;$("next").disabled=state.page*state.limit>=state.total;renderChecks(data.quotations);}
  function actions(q){return `<div class="row-actions"><button data-action="view" data-id="${q.id}">View</button><button data-action="payment" data-id="${q.id}">Payment</button><button data-action="print" data-id="${q.id}">Print/PDF</button><button data-action="share" data-id="${q.id}">WhatsApp</button><button data-action="revise" data-id="${q.id}">Revise</button><button data-action="void" data-id="${q.id}">Void</button></div>`}
  function quoteRow(q){return `<tr><td><strong>${escape(q.quote_number)}</strong></td><td>${escape(q.quotation_date)}</td><td>${escape(q.customer_name||q.customer_type||"Walk-in")}<br><small>${escape(q.customer_phone||"")}</small></td><td>${q.quotation_items?.[0]?.count||0}</td><td>${money(q.grand_total)}</td><td>${money(q.amount_paid)}</td><td>${money(q.balance_due)}</td><td><span class="badge ${q.payment_status}">${q.payment_status.replace("_"," ")}</span></td><td><span class="badge ${q.status}">${q.status}</span></td><td>${actions(q)}</td></tr>`}
  function quoteCard(q){return `<article class="quote-card"><strong>${escape(q.quote_number)}</strong><p>${escape(q.customer_name||q.customer_type||"Walk-in")} · ${escape(q.quotation_date)}</p><p>Total ${money(q.grand_total)} · Balance ${money(q.balance_due)}</p><p><span class="badge ${q.payment_status}">${q.payment_status.replace("_"," ")}</span> <span class="badge ${q.status}">${q.status}</span></p>${actions(q)}</article>`}
  async function handleQuoteAction(e){const button=e.target.closest("button[data-action]");if(!button)return;const id=button.dataset.id,action=button.dataset.action;if(action==="payment"){openPayment(id);return}if(action==="void"){const reason=prompt("Reason for voiding this quotation:");if(reason&&await api(`/api/quotes/${id}/void`,{method:"POST",body:JSON.stringify({reason})})){toast("Quotation voided.");refresh()}return}if(action==="revise"){if(confirm("Create a new revision of this finalised quotation?")&&await api(`/api/quotes/${id}/revise`,{method:"POST",body:"{}"})){toast("Revision created.");refresh()}return}const data=await api(`/api/admin/quotations/${id}`);if(!data)return;if(action==="view")showDetail(data.quotation);if(action==="print")printRemote(data.quotation);if(action==="share")shareRemote(data.quotation);}
  function showDetail(q){const items=q.quotation_items||[],payments=q.payments||[],events=q.quotation_events||[];$("detail-content").innerHTML=`<div class="detail-grid"><div class="detail-block"><b>${escape(q.quote_number)}</b><br>${escape(q.customer_name||q.customer_type||"Walk-in")}<br>${escape(q.customer_phone||"")}</div><div class="detail-block">Total: <b>${money(q.grand_total)}</b><br>Paid: ${money(q.amount_paid)}<br>Balance: ${money(q.balance_due)}</div></div><h3>Services</h3>${items.map(i=>`<p>${escape(i.item_name)} · ${i.quantity} ${escape(i.unit_type)} · ${money(i.line_total)}</p>`).join("")}<h3>Payments</h3>${payments.map(p=>`<p>${date(p.payment_date)} · ${escape(p.payment_method)} · ${money(p.amount)} · ${escape(p.status)} ${p.status==="active"?`<button data-reverse="${p.id}" data-quote="${q.id}">Reverse</button>`:""}</p>`).join("")||"<p>No payments.</p>"}<h3>Activity</h3>${events.sort((a,b)=>b.event_time.localeCompare(a.event_time)).map(e=>`<p>${date(e.event_time)} · ${escape(e.event_type.replaceAll("_"," "))}</p>`).join("")}`;$("detail-dialog").showModal();}
  async function reversePayment(e){const button=e.target.closest("button[data-reverse]");if(!button)return;const reason=prompt("Reason for reversing this payment:");if(!reason)return;const data=await api(`/api/quotes/${button.dataset.quote}/payments/${button.dataset.reverse}/reverse`,{method:"POST",body:JSON.stringify({reason})});if(data){$("detail-dialog").close();toast("Payment reversed; the original record was preserved.");refresh()}}
  function openPayment(id){$("payment-quote-id").value=id;$("payment-error").textContent="";$("payment-dialog").showModal();}
  async function savePayment(e){e.preventDefault();const method=$("payment-method").value,reference=$("payment-reference").value.trim();if(["mpesa","bank","card"].includes(method)&&!reference){$("payment-error").textContent="A reference is required for this payment method.";return}const data=await api(`/api/quotes/${$("payment-quote-id").value}/payments`,{method:"POST",body:JSON.stringify({amount:$("payment-amount").value,paymentMethod:method,paymentDate:$("payment-date").value,paymentReference:reference,notes:$("payment-notes").value})});if(data){$("payment-dialog").close();$("payment-form").reset();$("payment-date").value=new Date().toISOString().slice(0,16);toast("Payment recorded.");refresh()}}
  function printable(q){return `<!doctype html><title>FreshFold Quotation - ${escape(q.customer_name||q.customer_phone||q.quote_number)}</title><style>body{font:14px Arial;color:#10263f;max-width:800px;margin:auto;padding:30px}img{width:200px}header{display:flex;justify-content:space-between;border-bottom:3px solid #05aeba;padding-bottom:15px}table{width:100%;border-collapse:collapse;margin-top:20px}th,td{padding:9px;border-bottom:1px solid #ddd;text-align:left}.totals{width:320px;margin:20px 0 0 auto}.totals p{display:flex;justify-content:space-between}.grand{background:#073f78;color:white;padding:12px}.payment{background:#ecfafa;padding:12px;margin-top:20px}@page{size:A4;margin:0}body{padding:12mm}</style><header><img src="/data/logobg.png"><div><h2>${escape(q.quote_number)}</h2><p>${escape(q.quotation_date)}</p></div></header><p><b>${escape(q.customer_name||q.customer_type||"Walk-in")}</b><br>${escape(q.customer_phone||"")}<br>${escape(q.customer_location||"")}</p><table><tr><th>Service</th><th>Qty</th><th>Unit</th><th>Price</th><th>Total</th></tr>${(q.quotation_items||[]).map(i=>`<tr><td>${escape(i.item_name)}</td><td>${i.quantity}</td><td>${escape(i.unit_type)}</td><td>${money(i.unit_price)}</td><td>${money(i.line_total)}</td></tr>`).join("")}</table><div class="totals"><p><span>Subtotal</span><b>${money(q.subtotal)}</b></p><p><span>Discount</span><b>${money(q.discount_amount)}</b></p><p class="grand"><span>Grand total</span><b>${money(q.grand_total)}</b></p><p><span>Paid</span><b>${money(q.amount_paid)}</b></p><p><span>Balance</span><b>${money(q.balance_due)}</b></p></div><div class="payment"><b>Payment through Pochi la Biashara</b><br>0741179804</div><p>Call / WhatsApp: 0100677971</p><p>Thank you for choosing FreshFold Laundry.</p>`}
  async function printRemote(q){await api(`/api/quotes/${q.id}/events`,{method:"POST",body:JSON.stringify({eventType:"print_initiated"})});const popup=open("","_blank");popup.document.write(printable(q));popup.document.close();popup.onload=()=>{popup.print();api(`/api/quotes/${q.id}/events`,{method:"POST",body:JSON.stringify({eventType:"print_dialog_closed"})})};}
  async function shareRemote(q){const lines=(q.quotation_items||[]).map(i=>`• ${i.item_name} × ${i.quantity} — ${money(i.line_total)}`).join("\n"),message=`FreshFold Laundry\nQuotation ${q.quote_number}\nCustomer: ${q.customer_name||q.customer_type||"Walk-in"}\n\n${lines}\n\nGrand total: ${money(q.grand_total)}\nAmount paid: ${money(q.amount_paid)}\nBalance: ${money(q.balance_due)}\n\nPochi la Biashara: 0741179804\nCall / WhatsApp: 0100677971`;await api(`/api/quotes/${q.id}/events`,{method:"POST",body:JSON.stringify({eventType:"whatsapp_shared"})});open(`https://wa.me/${phone(q.customer_phone)}?text=${encodeURIComponent(message)}`,"_blank","noopener")}
  function renderChecks(quotes){const checks=[];quotes.forEach(q=>{if(q.status==="finalised"&&Number(q.amount_paid)===0)checks.push(`${q.quote_number}: finalised with no payment`);if(q.payment_status==="partially_paid")checks.push(`${q.quote_number}: partially paid`);if(q.payment_status==="overpaid")checks.push(`${q.quote_number}: overpaid`);if(q.status==="voided")checks.push(`${q.quote_number}: voided quotation`);if(q.status==="draft")checks.push(`${q.quote_number}: draft not finalised`)});$("checks").innerHTML=checks.slice(0,20).map(x=>`<div class="check"><strong>Review</strong> · ${escape(x)}</div>`).join("")||"<p>No review warnings in this result set.</p>";}
  function scanLocal(){let records=[];try{records=JSON.parse(localStorage.getItem("freshfoldSavedQuotes")||"[]")}catch{}if(!records.length){$("import-preview").innerHTML="<p>No local saved quotations found in this browser.</p>";return}$("import-preview").innerHTML=`<p><b>${records.length}</b> local quotations found. Review this count before importing.</p><button id="confirm-import">Import validated quotations</button>`;$("confirm-import").onclick=async()=>{if(!confirm(`Import ${records.length} local quotations? Existing quote numbers will be skipped.`))return;const data=await api("/api/admin/import",{method:"POST",body:JSON.stringify({quotations:records})});if(data){toast(`Imported ${data.imported}; skipped ${data.skipped}.`);refresh()}}}
  function exportCsv(){const url=`/api/admin/export?from=${state.from}&to=${state.to}`;fetch(url,{headers:{Authorization:`Bearer ${state.session.access_token}`}}).then(async r=>{if(!r.ok)throw new Error();const blob=await r.blob(),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`freshfold-report-${state.from}-${state.to}.csv`;a.click();URL.revokeObjectURL(a.href)}).catch(()=>toast("Export failed.",true));}
  function toast(message,error=false){const el=$("orders-toast");el.textContent=message;el.className=`orders-toast show${error?" error":""}`;clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove("show"),3500)}
  function phone(v){const d=String(v||"").replace(/\D/g,"");return d.startsWith("0")?`254${d.slice(1)}`:d}
  function isoDate(d){return new Intl.DateTimeFormat("en-CA",{timeZone:state.timezone,year:"numeric",month:"2-digit",day:"2-digit"}).format(d)}
  function addDays(d,n){const x=new Date(d);x.setDate(x.getDate()+n);return x}
  function debounce(fn,ms){let timer;return(...args)=>{clearTimeout(timer);timer=setTimeout(()=>fn(...args),ms)}}
})();
